name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Android Build Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libssl-dev libffi-dev libsqlite3-dev tk-dev libgdbm-compat-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libgomp1

      - name: Install Buildozer and Cython
        run: |
          python -m pip install --upgrade pip
          pip install cython virtualenv buildozer

      # 🔥 EL VERDADERO TRUCO: Borramos el SDK conflictivo de GitHub Actions
      # Esto obliga a Buildozer a descargar herramientas limpias y actualizadas automáticamente
      - name: Clear Pre-installed Android SDK to avoid conflicts
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /home/runner/.buildozer

      - name: Build APK
        env:
          APP_ALLOW_ROOT: "1"
        run: |
          buildozer android clean
          buildozer -v android debug

      # Cambiamos la ruta de subida a la carpeta estándar 'bin/' que es donde Buildozer deja el APK final
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: calculadora-debug-apk
          path: bin/*.apk
